# Generated by Django 3.2.4 on 2021-06-23 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='username',
            field=models.CharField(default=models.CharField(max_length=50), max_length=50, unique=True),
        ),
    ]
